# Configuration Netlify pour Velo-Altitude
# Mise à jour : Avril 2025 - Configuration finale pour déploiement de production

[build]
  command = "npm ci && NODE_ENV=production CI=false npm run build:prod"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"

# Variables d'environnement spécifiques à Velo-Altitude
[context.production.environment]
  REACT_APP_ENV = "production"
  REACT_APP_API_URL = "https://velo-altitude.netlify.app/api"
  REACT_APP_BASE_URL = "https://velo-altitude.netlify.app"
  REACT_APP_AUTH0_DOMAIN = "velo-altitude.eu.auth0.com"
  REACT_APP_AUTH0_CLIENT_ID = "yourClientId"
  REACT_APP_AUTH0_AUDIENCE = "https://api.velo-altitude.app"
  REACT_APP_MAPBOX_TOKEN = "yourMapboxToken"
  REACT_APP_OPENWEATHER_API_KEY = "yourOpenWeatherKey"

# Configuration des en-têtes pour la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self'; object-src 'none'; media-src 'self'; frame-src 'self';"

# Configuration du cache pour les ressources statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des redirections pour les APIs (pour prendre en charge les services refactorisés)
[[redirects]]
  from = "/api/cols/*"
  to = "/.netlify/functions/cols/:splat"
  status = 200

[[redirects]]
  from = "/api/weather/*"
  to = "/.netlify/functions/weather/:splat"
  status = 200

[[redirects]]
  from = "/api/nutrition/*"
  to = "/.netlify/functions/nutrition/:splat"
  status = 200

[[redirects]]
  from = "/api/challenges/*"
  to = "/.netlify/functions/challenges/:splat"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirection pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
