# Configuration Netlify pour Velo-Altitude
# Mise à jour : Avril 2025 - Configuration optimisée pour l'authentification et les performances

[build]
  publish = "client/build"
  command = "cd client && npm ci && DISABLE_ESLINT_PLUGIN=true CI=false npm run build && node ../scripts/deploy-complete.js"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "9.8.0"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  # Force un build sans cache
  NETLIFY_USE_YARN = "false"
  NETLIFY_YARN_WORKSPACES = "false"
  NETLIFY_CACHE_BUST = "true"
  ENABLE_BROTLI_COMPRESSION = "true"

# Configuration de traitement des assets
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Redirection pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimisation de cache pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Entêtes de sécurité pour toutes les pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.mapbox.com https://*.auth0.com https://api.openweathermap.org https://api.strava.com https://api.openrouteservice.org https://*.netlify.app https://api.anthropic.com https://api.openai.com; script-src 'self' 'unsafe-inline' https://*.mapbox.com https://*.auth0.com; style-src 'self' 'unsafe-inline' https://*.mapbox.com; img-src 'self' data: blob: https://*.mapbox.com https://openweathermap.org;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"
