# Configuration Netlify pour Velo-Altitude
# Mise à jour : Avril 2025 - Configuration pour gentle-donut-7fa5d8

[build]
  command = "npm run build:netlify"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"

# Variables d'environnement spécifiques à Velo-Altitude
[context.production.environment]
  REACT_APP_ENV = "production"
  REACT_APP_API_URL = "https://velo-altitude.com/api"
  REACT_APP_BASE_URL = "https://velo-altitude.com"

# Configuration des en-têtes pour la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Configuration du cache pour les ressources statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirection pour SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
