[build]
  command = "npm run netlify-build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Règle de redirection pour les API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Règle de redirection pour le routage SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://api.mapbox.com; style-src 'self' 'unsafe-inline' https://api.mapbox.com; img-src 'self' data: https://api.mapbox.com https://openweathermap.org; connect-src 'self' https://api.mapbox.com https://openweathermap.org https://*.auth0.com https://api.openrouteservice.org https://api.strava.com; frame-src 'self' https://*.auth0.com;"

# Configuration du cache pour les ressources statiques
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/**/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des plugins Netlify
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-hashfiles"
