# Configuration Netlify pour Velo-Altitude
# Mise à jour : Avril 2025 - Configuration finale pour déploiement de production

[build]
  command = "npm ci && npm run build:prod"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.2.0"
  NPM_VERSION = "8.0.0"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"

# Configuration de traitement des assets
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true

# Configuration des en-têtes HTTP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Configuration des en-têtes pour les chunks JavaScript et CSS
[[headers]]
  for = "/static/js/*chunk*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*chunk*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des en-têtes pour les ressources statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des en-têtes pour les images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Configuration des en-têtes pour les fonts
[[headers]]
  for = "/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des redirections pour l'authentification
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirection pour SPA - toutes les routes non correspondantes sont gérées par React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
