import React from 'react';
import { 
  FiInbox, 
  FiAlertTriangle, 
  FiEdit2, 
  FiThumbsUp, 
  FiFlag, 
  FiTrash2, 
  FiSend, 
  FiMessageSquare, 
  FiMessageCircle,
  FiClock,
  FiTarget,
  FiBriefcase,
  FiShield,
  FiThermometer,
  FiTool,
  FiBluetooth,
  FiMonitor,
  FiCpu,
  FiLifeBuoy,
  FiArrowLeft,
  FiCalendar,
  FiTrendingUp,
  FiDownload,
  FiShare2,
  FiHeart,
  FiMail,
  FiExternalLink,
  FiUser,
  FiInfo,
  FiActivity,
  FiZap
} from 'react-icons/fi';

// Importer d'autres icônes au besoin
import { MdShowChart as ShowChart } from 'react-icons/md';

// Créer un objet d'icônes pour faciliter l'accès
const Icons = {
  FiInbox,
  FiAlertTriangle,
  FiEdit2,
  FiThumbsUp,
  FiFlag,
  FiTrash2,
  FiSend,
  FiMessageSquare,
  FiMessageCircle,
  FiClock,
  FiTarget,
  FiBriefcase,
  FiShield,
  FiThermometer,
  FiTool,
  FiBluetooth,
  FiMonitor,
  FiCpu,
  FiLifeBuoy,
  FiArrowLeft,
  FiCalendar,
  FiTrendingUp,
  FiDownload,
  FiShare2,
  FiHeart,
  FiMail,
  FiExternalLink,
  FiUser,
  FiInfo,
  FiActivity,
  FiZap,
  ShowChart
};

export default Icons;

// Exporter aussi individuellement pour un accès direct
export {
  FiInbox,
  FiAlertTriangle,
  FiEdit2,
  FiThumbsUp,
  FiFlag,
  FiTrash2,
  FiSend,
  FiMessageSquare,
  FiMessageCircle,
  FiClock,
  FiTarget,
  FiBriefcase,
  FiShield,
  FiThermometer,
  FiTool,
  FiBluetooth,
  FiMonitor,
  FiCpu,
  FiLifeBuoy,
  FiArrowLeft,
  FiCalendar,
  FiTrendingUp,
  FiDownload,
  FiShare2,
  FiHeart,
  FiMail,
  FiExternalLink,
  FiUser,
  FiInfo,
  FiActivity,
  FiZap,
  ShowChart
};
